version: "2"
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=marvel
    ports:
      - "33060:3306"
  web:
    image: uqitsss/symfony-php7-xdebug
    environment:
      - APP_RUN_MODE=dev
    ports:
      - "8080:80"
      - "4430:443"
    volumes:
      - ./:/php
      - ./var/logs:/logs
    working_dir: /php
    depends_on:
      - mysql
    links:
      - mysql
  build: &defaults
    image: node:8.1
    volumes:
      - ./:/php
    working_dir: /php
    depends_on:
      - web
  sass: 
    <<: *defaults
    command: npm rebuild node-sass
  watch:
    <<: *defaults
    command: yarn assets:watch
    depends_on: [ sass ]
    depends_on:
      - sass