# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation

home:
  path: /
  defaults: { _controller: AppBundle:Home:index }

character_list:
  path: /characters
  defaults: { _controller: AppBundle:Character:index }

character_show:
  path: /characters/{id}
  defaults: { _controller: AppBundle:Character:show }