security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        database:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /